spring:
  webflux:
    base-path: /api/v1
  r2dbc:
    url: r2dbc:postgresql://pg-flex-prueba-tecnica-backend.postgres.database.azure.com:5432/postgres?ssl=true&sslmode=require&schema=prueba_tecnica
    username: adminpg
    password: ComplexP@ssw0rd!

  application:
    name: backend

server:
  port: 8001

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    url: /v3/api-docs
  info:
    title: Acme Airlines API
    version: 1.0.0
